version: '1.0'
name: nestjs_tutorial
services:
  database:
    image: postgres:latest
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/log:/var/log/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_tutorial
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: Asia/Seoul
